#!/bin/bash

COMMIT_MSG_FILE="$1"
COMMIT_MSG=$(head -n 1 "$COMMIT_MSG_FILE")

# Vérifie le format "KAN <nombres> <description>"
if ! [[ "$COMMIT_MSG" =~ ^KAN\ [0-9]+\ .+ ]]; then
  echo "❌ Format invalide."
  echo "📌 Utilise : KAN <numéro> <description>"
  echo "Exemple : KAN 01 Ajouter un système de login"
  exit 1
fi

exit 0
